import React, { Component } from 'react';
import './Alerts.css';
import { useState, useEffect} from 'react';

class Alerts extends Component {
    constructor(props) {
        super(props);
        console.log(props);
    }
    
    render() {
        return (
            <div className="alerts-container">
                <div className="alerts-title">
                    <h2>Alerts</h2>
                    <p>Alerts play a crucial role in cybersecurity applications by notifying users or security personnel of potential threats, attacks, or vulnerabilities in a system or network. 
These alerts can be generated by various sources, such as intrusion detection systems (IDS), firewalls, antivirus software, or threat intelligence feeds.</p>
                </div>

            </div>
        );
    }
}

export default Alerts